//go:build linux

package service

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

const sudoersDropInPath = "/etc/sudoers.d/rt-node-agent"

// sudoersDropIn grants the agent user the minimum systemctl rights it needs
// for POST /actions/service. The pattern is HARDCODED to rt-vllm-*.service —
// operators must name their vLLM units accordingly. This is the safety rail:
// a misconfigured config.yaml allowlist cannot escalate this drop-in into
// permission to stop sshd / docker / etc.
const sudoersDropIn = `# Auto-generated by rt-node-agent install. Do not edit by hand.
# Grants the rt-agent service user permission to control rt-vllm-*.service
# units (and ONLY those units) via POST /actions/service.
#
# The wildcard pattern is intentional: operators name vLLM model services
# rt-vllm-<model>.service; the agent never spawns or creates units, only
# acts on existing ones declared in /etc/rt-node-agent/config.yaml.
rt-agent ALL=(root) NOPASSWD: /bin/systemctl start rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /bin/systemctl stop rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /bin/systemctl restart rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /bin/systemctl status rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /bin/systemctl show rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /usr/bin/systemctl start rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /usr/bin/systemctl stop rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /usr/bin/systemctl restart rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /usr/bin/systemctl status rt-vllm-[a-zA-Z0-9_-]*.service, \
                              /usr/bin/systemctl show rt-vllm-[a-zA-Z0-9_-]*.service
`

// installSudoersDropIn writes the drop-in atomically and validates it with
// visudo before placing it. A bad drop-in can lock all sudo users out on
// some distros; validation prevents that class of foot-gun.
func installSudoersDropIn() error {
	if os.Geteuid() != 0 {
		return fmt.Errorf("root required")
	}
	// visudo -cf <file> exits non-zero on syntax error.
	tmp, err := os.CreateTemp("", "rt-node-agent-sudoers-*.tmp")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.WriteString(sudoersDropIn); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if _, err := exec.LookPath("visudo"); err == nil {
		cmd := exec.Command("visudo", "-cf", tmpPath)
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("visudo check failed: %v: %s", err, out)
		}
	}
	// Sudoers drop-ins must be 0440 and live in /etc/sudoers.d/.
	if err := os.MkdirAll(filepath.Dir(sudoersDropInPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(sudoersDropInPath, []byte(sudoersDropIn), 0o440); err != nil {
		return err
	}
	return nil
}

// removeSudoersDropIn deletes the drop-in. Safe to call when absent.
func removeSudoersDropIn() error {
	if err := os.Remove(sudoersDropInPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
